-- AlterTable
ALTER TABLE "users" ADD COLUMN     "lastTokenReset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "responseQualityLevel" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "tokensUsedToday" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalTokensUsed" INTEGER NOT NULL DEFAULT 0;
