import { Metadata } from 'next';

export interface SEOConfig {
  title: string;
  description: string;
  keywords?: string[];
  image?: string;
  noIndex?: boolean;
  canonical?: string;
  type?: 'website' | 'article' | 'service';
  publishedTime?: string;
  modifiedTime?: string;
  author?: string;
  schema?: any;
}

const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://talkers.pro';
const siteName = 'Talkers - Connect with Cherished Memories';

// Core grief support and memorial service keywords
const coreKeywords = [
  'grief support platform',
  'bereavement support online',
  'memorial conversations ai',
  'grief counseling technology',
  'digital grief support',
  'online grief help',
  'ai memorial service',
  'grief support platform',
  'connect with deceased loved ones',
  'whatsapp memories ai',
  'digital memorial conversations',
  'bereavement support technology',
  'memorial ai chat',
  'grief healing through ai',
  'deceased loved one conversations',
  'memorial message preservation',
  'ai powered grief support',
  'virtual memorial service',
  'death anniversary support',
  'remembrance platform',
  'grief recovery tools',
  'memorial conversation ai',
  'bereavement chatbot',
  'deceased family member chat',
  'grief therapy platform',
  'losing a parent grief',
  'spouse death support',
  'child loss grief help',
  'pet loss bereavement',
  'sudden death grief support',
  'complicated grief counseling',
  'grief stages explained',
  'how to cope with grief',
  'grief support groups online',
  'memorial preservation digital',
  // High-volume grief support keywords
  'grief support',
  'grief counseling',
  'bereavement support',
  'grief therapy',
  'grief help',
  'bereavement counseling',
  'grief support near me',
  'grief counseling near me',
  'bereavement support near me',
  'grief counselor near me',
  'grief therapist near me',
  'online grief support',
  'online grief counseling',
  'virtual grief therapy',
  'grief support groups',
  'bereavement groups',
  'grief chat support',
  'free grief support',
  '24/7 grief help',
  'immediate grief support',
  'grief crisis support',
  'grief support chat',
  'grief help online',
  'bereavement help',
  'grief assistance',
  'mourning support',
  'loss support',
  'death grief support',
  'funeral grief support',
  'grief recovery',
  'grief healing',
  'grief coping',
  'grief management',
  'grief counseling services',
  'professional grief support',
  'licensed grief counselor',
  'certified grief therapist',
  'grief support specialist',
  'bereavement specialist',
  'grief intervention',
  'grief treatment',
  'grief therapy sessions',
  'grief counseling sessions',
  'individual grief counseling',
  'group grief therapy',
  'family grief counseling',
  'child grief support',
  'teen grief counseling',
  'adult grief therapy',
  'senior grief support',
  'widow grief support',
  'widower support',
  'parent loss grief',
  'child loss support',
  'spouse loss grief',
  'sibling loss support',
  'pet loss grief',
  'sudden loss support',
  'traumatic loss support',
  'suicide loss support',
  'overdose loss support',
  'accident loss grief',
  'illness loss support',
  'cancer loss grief',
  'covid loss support',
  'miscarriage grief support',
  'stillbirth support',
  'infant loss grief',
  'pregnancy loss support',
  'anticipatory grief support',
  'complicated grief therapy',
  'prolonged grief support',
  'disenfranchised grief',
  'ambiguous loss support',
  'grief and depression',
  'grief and anxiety',
  'grief and trauma',
  'grief and ptsd',
  'grief medication',
  'grief psychiatrist',
  'grief psychologist',
  'grief social worker',
  'grief chaplain',
  'grief spiritual support',
  'religious grief support',
  'christian grief support',
  'jewish grief support',
  'muslim grief support',
  'buddhist grief support',
  'secular grief support',
  'non religious grief support',
  'grief support without religion',
  'grief support for atheists',
  'grief support for agnostics',
  'lgbtq grief support',
  'military grief support',
  'veteran grief support',
  'first responder grief',
  'healthcare worker grief',
  'caregiver grief support',
  'workplace grief support',
  'employee grief assistance',
  'grief leave support',
  'bereavement leave help',
  'grief at work',
  'returning to work after loss',
  'grief and productivity',
  'grief and concentration',
  'grief brain fog',
  'grief memory problems',
  'grief sleep issues',
  'grief appetite changes',
  'grief physical symptoms',
  'grief body aches',
  'grief fatigue',
  'grief exhaustion',
  'grief anger',
  'grief guilt',
  'grief regret',
  'grief shame',
  'grief numbness',
  'grief denial',
  'grief bargaining',
  'grief depression',
  'grief acceptance',
  'grief stages',
  'kubler ross grief',
  'grief models',
  'grief theories',
  'grief research',
  'grief studies',
  'grief psychology',
  'grief neuroscience',
  'grief brain science',
  'grief hormones',
  'grief chemicals',
  'grief dopamine',
  'grief serotonin',
  'grief cortisol',
  'grief stress response',
  'grief fight or flight',
  'grief nervous system',
  'grief immune system',
  'grief health effects',
  'grief medical issues',
  'grief heart problems',
  'grief blood pressure',
  'grief diabetes',
  'grief autoimmune',
  'grief inflammation',
  'grief pain',
  'grief headaches',
  'grief migraines',
  'grief stomach issues',
  'grief digestive problems',
  'grief nausea',
  'grief diarrhea',
  'grief constipation',
  'grief weight loss',
  'grief weight gain',
  'grief eating disorders',
  'grief anorexia',
  'grief bulimia',
  'grief binge eating',
  'grief substance abuse',
  'grief alcohol abuse',
  'grief drug abuse',
  'grief addiction',
  'grief recovery addiction',
  'grief relapse prevention',
  'grief sobriety support',
  'grief aa support',
  'grief na support',
  'grief dual diagnosis',
  'grief mental health',
  'grief psychiatric care',
  'grief medication management',
  'grief antidepressants',
  'grief anxiety medication',
  'grief sleep medication',
  'grief natural remedies',
  'grief supplements',
  'grief vitamins',
  'grief herbs',
  'grief essential oils',
  'grief meditation',
  'grief mindfulness',
  'grief yoga',
  'grief exercise',
  'grief walking',
  'grief running',
  'grief swimming',
  'grief dancing',
  'grief art therapy',
  'grief music therapy',
  'grief dance therapy',
  'grief drama therapy',
  'grief poetry therapy',
  'grief writing therapy',
  'grief journaling',
  'grief blogging',
  'grief storytelling',
  'grief memoir writing',
  'grief creative expression',
  'grief art',
  'grief music',
  'grief photography',
  'grief scrapbooking',
  'grief memory books',
  'grief memorial projects',
  'grief rituals',
  'grief ceremonies',
  'grief traditions',
  'grief customs',
  'grief cultural practices',
  'grief religious practices',
  'grief spiritual practices',
  'grief prayer',
  'grief meditation practices',
  'grief mindfulness practices',
  'grief breathing exercises',
  'grief relaxation techniques',
  'grief stress management',
  'grief coping strategies',
  'grief coping skills',
  'grief coping mechanisms',
  'grief survival strategies',
  'grief self care',
  'grief self help',
  'grief self compassion',
  'grief self forgiveness',
  'grief self acceptance',
  'grief self love',
  'grief boundaries',
  'grief saying no',
  'grief energy management',
  'grief time management',
  'grief decision making',
  'grief problem solving',
  'grief communication',
  'grief relationships',
  'grief family dynamics',
  'grief friendship changes',
  'grief social support',
  'grief isolation',
  'grief loneliness',
  'grief connection',
  'grief community',
  'grief belonging',
  'grief identity',
  'grief purpose',
  'grief meaning',
  'grief hope',
  'grief faith',
  'grief spirituality',
  'grief afterlife beliefs',
  'grief heaven',
  'grief reincarnation',
  'grief energy',
  'grief spirit',
  'grief soul',
  'grief consciousness',
  'grief dreams',
  'grief visitations',
  'grief signs',
  'grief messages',
  'grief communication after death',
  'grief mediumship',
  'grief psychic readings',
  'grief paranormal experiences',
  'grief supernatural',
  'grief miracles',
  'grief synchronicities',
  'grief coincidences',
  'grief symbols',
  'grief animals',
  'grief nature',
  'grief seasons',
  'grief weather',
  'grief holidays',
  'grief birthdays',
  'grief anniversaries',
  'grief christmas',
  'grief thanksgiving',
  'grief new year',
  'grief valentines day',
  'grief mothers day',
  'grief fathers day',
  'grief memorial day',
  'grief veterans day',
  'grief independence day',
  'grief halloween',
  'grief easter',
  'grief passover',
  'grief ramadan',
  'grief diwali',
  'grief chinese new year',
  'grief cultural holidays',
  'grief religious holidays',
  'grief secular holidays',
  'grief family traditions',
  'grief new traditions',
  'grief tradition changes',
  'grief celebration of life',
  'grief memorial services',
  'grief funeral planning',
  'grief burial decisions',
  'grief cremation decisions',
  'grief obituary writing',
  'grief eulogy writing',
  'grief memorial speeches',
  'grief tribute videos',
  'grief photo displays',
  'grief memory tables',
  'grief guest books',
  'grief memorial donations',
  'grief scholarship funds',
  'grief charity giving',
  'grief volunteer work',
  'grief advocacy',
  'grief awareness',
  'grief education',
  'grief prevention',
  'grief intervention',
  'grief early intervention',
  'grief screening',
  'grief assessment',
  'grief diagnosis',
  'grief treatment planning',
  'grief case management',
  'grief care coordination',
  'grief multidisciplinary care',
  'grief team approach',
  'grief collaborative care',
  'grief integrated care',
  'grief holistic care',
  'grief whole person care',
  'grief person centered care',
  'grief trauma informed care',
  'grief culturally sensitive care',
  'grief culturally competent care',
  'grief diversity',
  'grief inclusion',
  'grief equity',
  'grief social justice',
  'grief human rights',
  'grief dignity',
  'grief respect',
  'grief compassion',
  'grief empathy',
  'grief understanding',
  'grief validation',
  'grief normalization',
  'grief psychoeducation',
  'grief information',
  'grief resources',
  'grief tools',
  'grief apps',
  'grief websites',
  'grief books',
  'grief podcasts',
  'grief videos',
  'grief documentaries',
  'grief movies',
  'grief tv shows',
  'grief music',
  'grief songs',
  'grief playlists',
  'grief quotes',
  'grief poems',
  'grief prayers',
  'grief affirmations',
  'grief mantras',
  'grief meditations',
  'grief guided imagery',
  'grief visualization',
  'grief hypnosis',
  'grief emdr',
  'grief cognitive behavioral therapy',
  'grief cbt',
  'grief dialectical behavior therapy',
  'grief dbt',
  'grief acceptance commitment therapy',
  'grief act',
  'grief mindfulness based therapy',
  'grief somatic therapy',
  'grief body work',
  'grief massage therapy',
  'grief acupuncture',
  'grief chiropractic care',
  'grief physical therapy',
  'grief occupational therapy',
  'grief speech therapy',
  'grief recreational therapy',
  'grief horticultural therapy',
  'grief animal therapy',
  'grief pet therapy',
  'grief equine therapy',
  'grief wilderness therapy',
  'grief adventure therapy',
  'grief outdoor therapy',
  'grief nature therapy',
  'grief ecotherapy',
  'grief environmental therapy',
  'grief green therapy',
  'grief forest bathing',
  'grief gardening therapy',
  'grief farming therapy',
  'grief agricultural therapy'
];

export function generateMetadata(config: SEOConfig): Metadata {
  const {
    title,
    description,
    keywords = [],
    image = `${baseUrl}/og-image.png`,
    noIndex = false,
    canonical,
    type = 'website'
  } = config;

  const fullTitle = title.includes('Talkers') ? title : `${title} | ${siteName}`;
  const allKeywords = [...coreKeywords, ...keywords].join(', ');

  return {
    title: fullTitle,
    description,
    keywords: allKeywords,
    authors: [{ name: 'Talkers Team' }],
    creator: 'Talkers',
    publisher: 'Talkers',
    formatDetection: {
      email: false,
      address: false,
      telephone: false,
    },
    metadataBase: new URL(baseUrl),
    alternates: {
      canonical: canonical || baseUrl,
    },
    robots: {
      index: !noIndex,
      follow: !noIndex,
      googleBot: {
        index: !noIndex,
        follow: !noIndex,
        'max-video-preview': -1,
        'max-image-preview': 'large',
        'max-snippet': -1,
      },
    },
    openGraph: {
      title: fullTitle,
      description,
      url: canonical || baseUrl,
      siteName,
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
      locale: 'en_US',
      type: type === 'article' ? 'article' : 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images: [image],
      creator: '@TalkersAI',
      site: '@TalkersAI',
    },
    verification: {
      google: process.env.GOOGLE_SITE_VERIFICATION,
      yandex: process.env.YANDEX_VERIFICATION,
      yahoo: process.env.YAHOO_VERIFICATION,
    },
    category: 'Health & Wellness',
  };
}

export function generateSchema(config: SEOConfig & { url: string }) {
  const { title, description, url, type, publishedTime, modifiedTime, author } = config;
  
  const baseSchema = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: siteName,
    url: baseUrl,
    logo: `${baseUrl}/logo.png`,
    description: 'AI-powered grief support platform helping people reconnect with deceased loved ones through preserved WhatsApp conversations',
    foundingDate: '2024',
    sameAs: [
      'https://twitter.com/TalkersAI',
      'https://facebook.com/TalkersAI',
      'https://linkedin.com/company/talkers-ai'
    ],
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '+1-800-TALKERS',
      contactType: 'customer service',
      availableLanguage: 'English'
    },
    address: {
      '@type': 'PostalAddress',
      addressCountry: 'US'
    }
  };

  const webPageSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: title,
    description,
    url,
    isPartOf: {
      '@type': 'WebSite',
      name: siteName,
      url: baseUrl
    },
    datePublished: publishedTime,
    dateModified: modifiedTime || new Date().toISOString(),
    author: author ? {
      '@type': 'Person',
      name: author
    } : undefined,
    publisher: {
      '@type': 'Organization',
      name: siteName,
      logo: {
        '@type': 'ImageObject',
        url: `${baseUrl}/logo.png`
      }
    }
  };

  const serviceSchema = {
    '@context': 'https://schema.org',
    '@type': 'Service',
    name: 'AI Memorial Conversation Service',
    description: 'Connect with deceased loved ones through AI-powered conversations using preserved WhatsApp messages',
    provider: {
      '@type': 'Organization',
      name: siteName,
      url: baseUrl
    },
    serviceType: 'Grief Support Technology',
    audience: {
      '@type': 'Audience',
      audienceType: 'Bereaved individuals and families'
    },
    category: 'Mental Health & Grief Support',
    hasOfferCatalog: {
      '@type': 'OfferCatalog',
      name: 'Memorial AI Services',
      itemListElement: [
        {
          '@type': 'Offer',
          itemOffered: {
            '@type': 'Service',
            name: 'Free Trial',
            description: '3-day trial with one conversation'
          }
        },
        {
          '@type': 'Offer',
          itemOffered: {
            '@type': 'Service',
            name: 'Premium Service',
            description: 'Unlimited conversations with advanced features'
          },
          price: '12',
          priceCurrency: 'USD'
        }
      ]
    }
  };

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How does Talkers help with grief?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Talkers uses AI to help you have meaningful conversations with deceased loved ones using your preserved WhatsApp messages, providing comfort and closure during the grieving process.'
        }
      },
      {
        '@type': 'Question',
        name: 'Is my data secure and private?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes, your memories and conversations are completely private and secure. We use enterprise-grade encryption and never share your personal data.'
        }
      },
      {
        '@type': 'Question',
        name: 'How do I upload WhatsApp conversations?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Simply export your WhatsApp chat history and upload it securely to our platform. Our AI will analyze the conversation patterns to enable meaningful interactions.'
        }
      }
    ]
  };

  return {
    baseSchema,
    webPageSchema,
    serviceSchema,
    faqSchema
  };
}

export const defaultSEO: SEOConfig = {
  title: 'Talkers - Connect with Cherished Memories Through AI',
  description: 'A sacred space to reconnect with deceased loved ones through AI-powered conversations using your WhatsApp messages. Preserve memories, find comfort, and heal through technology.',
  keywords: coreKeywords,
  type: 'website'
};

// Page-specific SEO configurations
export const pageConfigs = {
  home: {
    title: 'Talkers - AI Memorial Conversations with Deceased Loved Ones',
    description: 'Connect with deceased loved ones through AI-powered conversations using your WhatsApp messages. A gentle grief support platform for healing and remembrance.',
    keywords: ['ai memorial conversations', 'grief support platform', 'whatsapp memories', 'deceased loved ones chat']
  },
  about: {
    title: 'About Talkers - AI-Powered Grief Support & Memorial Platform',
    description: 'Learn how Talkers helps people heal through AI conversations with deceased loved ones. Our mission is to preserve memories and provide comfort through technology.',
    keywords: ['grief support technology', 'memorial ai platform', 'bereavement assistance']
  },
  pricing: {
    title: 'Pricing - Affordable Memorial AI Conversations | Talkers',
    description: 'Start your healing journey with our free trial. Premium plans from $12/month for unlimited conversations with deceased loved ones through AI.',
    keywords: ['memorial ai pricing', 'grief support cost', 'affordable memorial service']
  },
  privacy: {
    title: 'Privacy Policy - Secure Memorial Data Protection | Talkers',
    description: 'Your memories are sacred. Learn how we protect your personal data and conversations with enterprise-grade security and privacy measures.',
    keywords: ['memorial data privacy', 'secure grief platform', 'whatsapp data protection']
  },
  contact: {
    title: 'Contact Talkers - Get Support for Your Memorial AI Journey',
    description: 'Need help with your memorial conversations? Contact our compassionate support team for assistance with grief support and platform guidance.',
    keywords: ['grief support contact', 'memorial ai help', 'bereavement assistance']
  }
}; 